name: deploy docker
on:
  workflow_call:
    inputs:
      instance_ip:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-docker-echoinfo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set image version (tag)
        id: image_version
        run: echo "githash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: configure docker host
        uses: khaledez/configure-docker-host@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          host: ${{ inputs.instance_ip }}
          user: github
          
      - name: login and run
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/khaledez/echoinfo:${{ steps.image_version.outputs.githash }}
          docker run -d -e PORT=80 -p 80:80 ghcr.io/khaledez/echoinfo:${{ steps.image_version.outputs.githash }}

